// proto/razpravljalnica.proto

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: proto/razpravljalnica.proto

package razpravljalnica

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type OpType int32

const (
	OpType_OP_POST   OpType = 0
	OpType_OP_LIKE   OpType = 1
	OpType_OP_UNLIKE OpType = 2
)

// Enum value maps for OpType.
var (
	OpType_name = map[int32]string{
		0: "OP_POST",
		1: "OP_LIKE",
		2: "OP_UNLIKE",
	}
	OpType_value = map[string]int32{
		"OP_POST":   0,
		"OP_LIKE":   1,
		"OP_UNLIKE": 2,
	}
)

func (x OpType) Enum() *OpType {
	p := new(OpType)
	*p = x
	return p
}

func (x OpType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OpType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_razpravljalnica_proto_enumTypes[0].Descriptor()
}

func (OpType) Type() protoreflect.EnumType {
	return &file_proto_razpravljalnica_proto_enumTypes[0]
}

func (x OpType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OpType.Descriptor instead.
func (OpType) EnumDescriptor() ([]byte, []int) {
	return file_proto_razpravljalnica_proto_rawDescGZIP(), []int{0}
}

type User struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	PasswordHash  string                 `protobuf:"bytes,3,opt,name=password_hash,json=passwordHash,proto3" json:"password_hash,omitempty"`
	Salt          string                 `protobuf:"bytes,4,opt,name=salt,proto3" json:"salt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_proto_razpravljalnica_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_proto_razpravljalnica_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_proto_razpravljalnica_proto_rawDescGZIP(), []int{0}
}

func (x *User) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *User) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *User) GetPasswordHash() string {
	if x != nil {
		return x.PasswordHash
	}
	return ""
}

func (x *User) GetSalt() string {
	if x != nil {
		return x.Salt
	}
	return ""
}

type Topic struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Topic) Reset() {
	*x = Topic{}
	mi := &file_proto_razpravljalnica_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Topic) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Topic) ProtoMessage() {}

func (x *Topic) ProtoReflect() protoreflect.Message {
	mi := &file_proto_razpravljalnica_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Topic.ProtoReflect.Descriptor instead.
func (*Topic) Descriptor() ([]byte, []int) {
	return file_proto_razpravljalnica_proto_rawDescGZIP(), []int{1}
}

func (x *Topic) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Topic) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type Message struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	TopicId       int64                  `protobuf:"varint,2,opt,name=topic_id,json=topicId,proto3" json:"topic_id,omitempty"`
	UserId        int64                  `protobuf:"varint,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Text          string                 `protobuf:"bytes,4,opt,name=text,proto3" json:"text,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	TopicName     string                 `protobuf:"bytes,6,opt,name=topic_name,json=topicName,proto3" json:"topic_name,omitempty"`
	Likes         int32                  `protobuf:"varint,7,opt,name=likes,proto3" json:"likes,omitempty"`
	IsLiked       bool                   `protobuf:"varint,8,opt,name=is_liked,json=isLiked,proto3" json:"is_liked,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Message) Reset() {
	*x = Message{}
	mi := &file_proto_razpravljalnica_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_proto_razpravljalnica_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_proto_razpravljalnica_proto_rawDescGZIP(), []int{2}
}

func (x *Message) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Message) GetTopicId() int64 {
	if x != nil {
		return x.TopicId
	}
	return 0
}

func (x *Message) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *Message) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *Message) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Message) GetTopicName() string {
	if x != nil {
		return x.TopicName
	}
	return ""
}

func (x *Message) GetLikes() int32 {
	if x != nil {
		return x.Likes
	}
	return 0
}

func (x *Message) GetIsLiked() bool {
	if x != nil {
		return x.IsLiked
	}
	return false
}

type Like struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TopicId       int64                  `protobuf:"varint,1,opt,name=topic_id,json=topicId,proto3" json:"topic_id,omitempty"`
	MessageId     int64                  `protobuf:"varint,2,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	UserId        int64                  `protobuf:"varint,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Like) Reset() {
	*x = Like{}
	mi := &file_proto_razpravljalnica_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Like) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Like) ProtoMessage() {}

func (x *Like) ProtoReflect() protoreflect.Message {
	mi := &file_proto_razpravljalnica_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Like.ProtoReflect.Descriptor instead.
func (*Like) Descriptor() ([]byte, []int) {
	return file_proto_razpravljalnica_proto_rawDescGZIP(), []int{3}
}

func (x *Like) GetTopicId() int64 {
	if x != nil {
		return x.TopicId
	}
	return 0
}

func (x *Like) GetMessageId() int64 {
	if x != nil {
		return x.MessageId
	}
	return 0
}

func (x *Like) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type NodeInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Address       string                 `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeInfo) Reset() {
	*x = NodeInfo{}
	mi := &file_proto_razpravljalnica_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeInfo) ProtoMessage() {}

func (x *NodeInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_razpravljalnica_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeInfo.ProtoReflect.Descriptor instead.
func (*NodeInfo) Descriptor() ([]byte, []int) {
	return file_proto_razpravljalnica_proto_rawDescGZIP(), []int{4}
}

func (x *NodeInfo) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *NodeInfo) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

type CreateUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	Salt          string                 `protobuf:"bytes,3,opt,name=salt,proto3" json:"salt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateUserRequest) Reset() {
	*x = CreateUserRequest{}
	mi := &file_proto_razpravljalnica_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUserRequest) ProtoMessage() {}

func (x *CreateUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_razpravljalnica_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUserRequest.ProtoReflect.Descriptor instead.
func (*CreateUserRequest) Descriptor() ([]byte, []int) {
	return file_proto_razpravljalnica_proto_rawDescGZIP(), []int{5}
}

func (x *CreateUserRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateUserRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *CreateUserRequest) GetSalt() string {
	if x != nil {
		return x.Salt
	}
	return ""
}

type LoginRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginRequest) Reset() {
	*x = LoginRequest{}
	mi := &file_proto_razpravljalnica_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginRequest) ProtoMessage() {}

func (x *LoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_razpravljalnica_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginRequest.ProtoReflect.Descriptor instead.
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return file_proto_razpravljalnica_proto_rawDescGZIP(), []int{6}
}

func (x *LoginRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *LoginRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type GetUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserRequest) Reset() {
	*x = GetUserRequest{}
	mi := &file_proto_razpravljalnica_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserRequest) ProtoMessage() {}

func (x *GetUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_razpravljalnica_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserRequest.ProtoReflect.Descriptor instead.
func (*GetUserRequest) Descriptor() ([]byte, []int) {
	return file_proto_razpravljalnica_proto_rawDescGZIP(), []int{7}
}

func (x *GetUserRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type GetUserByIdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserByIdRequest) Reset() {
	*x = GetUserByIdRequest{}
	mi := &file_proto_razpravljalnica_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserByIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserByIdRequest) ProtoMessage() {}

func (x *GetUserByIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_razpravljalnica_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserByIdRequest.ProtoReflect.Descriptor instead.
func (*GetUserByIdRequest) Descriptor() ([]byte, []int) {
	return file_proto_razpravljalnica_proto_rawDescGZIP(), []int{8}
}

func (x *GetUserByIdRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type CreateTopicRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	UserId        int64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTopicRequest) Reset() {
	*x = CreateTopicRequest{}
	mi := &file_proto_razpravljalnica_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTopicRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTopicRequest) ProtoMessage() {}

func (x *CreateTopicRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_razpravljalnica_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTopicRequest.ProtoReflect.Descriptor instead.
func (*CreateTopicRequest) Descriptor() ([]byte, []int) {
	return file_proto_razpravljalnica_proto_rawDescGZIP(), []int{9}
}

func (x *CreateTopicRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateTopicRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type GetTopicRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTopicRequest) Reset() {
	*x = GetTopicRequest{}
	mi := &file_proto_razpravljalnica_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTopicRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTopicRequest) ProtoMessage() {}

func (x *GetTopicRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_razpravljalnica_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTopicRequest.ProtoReflect.Descriptor instead.
func (*GetTopicRequest) Descriptor() ([]byte, []int) {
	return file_proto_razpravljalnica_proto_rawDescGZIP(), []int{10}
}

func (x *GetTopicRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type PostMessageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TopicId       int64                  `protobuf:"varint,1,opt,name=topic_id,json=topicId,proto3" json:"topic_id,omitempty"`
	UserId        int64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Text          string                 `protobuf:"bytes,3,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PostMessageRequest) Reset() {
	*x = PostMessageRequest{}
	mi := &file_proto_razpravljalnica_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PostMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostMessageRequest) ProtoMessage() {}

func (x *PostMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_razpravljalnica_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostMessageRequest.ProtoReflect.Descriptor instead.
func (*PostMessageRequest) Descriptor() ([]byte, []int) {
	return file_proto_razpravljalnica_proto_rawDescGZIP(), []int{11}
}

func (x *PostMessageRequest) GetTopicId() int64 {
	if x != nil {
		return x.TopicId
	}
	return 0
}

func (x *PostMessageRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *PostMessageRequest) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type LikeMessageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TopicId       int64                  `protobuf:"varint,1,opt,name=topic_id,json=topicId,proto3" json:"topic_id,omitempty"`
	MessageId     int64                  `protobuf:"varint,2,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	UserId        int64                  `protobuf:"varint,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Like          bool                   `protobuf:"varint,4,opt,name=like,proto3" json:"like,omitempty"` // true = like, false = unlike
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LikeMessageRequest) Reset() {
	*x = LikeMessageRequest{}
	mi := &file_proto_razpravljalnica_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LikeMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LikeMessageRequest) ProtoMessage() {}

func (x *LikeMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_razpravljalnica_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LikeMessageRequest.ProtoReflect.Descriptor instead.
func (*LikeMessageRequest) Descriptor() ([]byte, []int) {
	return file_proto_razpravljalnica_proto_rawDescGZIP(), []int{12}
}

func (x *LikeMessageRequest) GetTopicId() int64 {
	if x != nil {
		return x.TopicId
	}
	return 0
}

func (x *LikeMessageRequest) GetMessageId() int64 {
	if x != nil {
		return x.MessageId
	}
	return 0
}

func (x *LikeMessageRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *LikeMessageRequest) GetLike() bool {
	if x != nil {
		return x.Like
	}
	return false
}

type ListTopicsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTopicsRequest) Reset() {
	*x = ListTopicsRequest{}
	mi := &file_proto_razpravljalnica_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTopicsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTopicsRequest) ProtoMessage() {}

func (x *ListTopicsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_razpravljalnica_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTopicsRequest.ProtoReflect.Descriptor instead.
func (*ListTopicsRequest) Descriptor() ([]byte, []int) {
	return file_proto_razpravljalnica_proto_rawDescGZIP(), []int{13}
}

func (x *ListTopicsRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type ListJoinableTopicsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListJoinableTopicsRequest) Reset() {
	*x = ListJoinableTopicsRequest{}
	mi := &file_proto_razpravljalnica_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListJoinableTopicsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListJoinableTopicsRequest) ProtoMessage() {}

func (x *ListJoinableTopicsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_razpravljalnica_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListJoinableTopicsRequest.ProtoReflect.Descriptor instead.
func (*ListJoinableTopicsRequest) Descriptor() ([]byte, []int) {
	return file_proto_razpravljalnica_proto_rawDescGZIP(), []int{14}
}

func (x *ListJoinableTopicsRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type ListTopicsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Topics        []*Topic               `protobuf:"bytes,1,rep,name=topics,proto3" json:"topics,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTopicsResponse) Reset() {
	*x = ListTopicsResponse{}
	mi := &file_proto_razpravljalnica_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTopicsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTopicsResponse) ProtoMessage() {}

func (x *ListTopicsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_razpravljalnica_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTopicsResponse.ProtoReflect.Descriptor instead.
func (*ListTopicsResponse) Descriptor() ([]byte, []int) {
	return file_proto_razpravljalnica_proto_rawDescGZIP(), []int{15}
}

func (x *ListTopicsResponse) GetTopics() []*Topic {
	if x != nil {
		return x.Topics
	}
	return nil
}

type GetMessagesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TopicId       int64                  `protobuf:"varint,1,opt,name=topic_id,json=topicId,proto3" json:"topic_id,omitempty"`
	FromMessageId int64                  `protobuf:"varint,2,opt,name=from_message_id,json=fromMessageId,proto3" json:"from_message_id,omitempty"`
	Limit         int32                  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	RequestUserId int64                  `protobuf:"varint,4,opt,name=request_user_id,json=requestUserId,proto3" json:"request_user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMessagesRequest) Reset() {
	*x = GetMessagesRequest{}
	mi := &file_proto_razpravljalnica_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMessagesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMessagesRequest) ProtoMessage() {}

func (x *GetMessagesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_razpravljalnica_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMessagesRequest.ProtoReflect.Descriptor instead.
func (*GetMessagesRequest) Descriptor() ([]byte, []int) {
	return file_proto_razpravljalnica_proto_rawDescGZIP(), []int{16}
}

func (x *GetMessagesRequest) GetTopicId() int64 {
	if x != nil {
		return x.TopicId
	}
	return 0
}

func (x *GetMessagesRequest) GetFromMessageId() int64 {
	if x != nil {
		return x.FromMessageId
	}
	return 0
}

func (x *GetMessagesRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *GetMessagesRequest) GetRequestUserId() int64 {
	if x != nil {
		return x.RequestUserId
	}
	return 0
}

type GetMessagesByUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TopicId       int64                  `protobuf:"varint,1,opt,name=topic_id,json=topicId,proto3" json:"topic_id,omitempty"`
	UserName      string                 `protobuf:"bytes,2,opt,name=user_name,json=userName,proto3" json:"user_name,omitempty"`
	Limit         int32                  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	RequestUserId int64                  `protobuf:"varint,4,opt,name=request_user_id,json=requestUserId,proto3" json:"request_user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMessagesByUserRequest) Reset() {
	*x = GetMessagesByUserRequest{}
	mi := &file_proto_razpravljalnica_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMessagesByUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMessagesByUserRequest) ProtoMessage() {}

func (x *GetMessagesByUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_razpravljalnica_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMessagesByUserRequest.ProtoReflect.Descriptor instead.
func (*GetMessagesByUserRequest) Descriptor() ([]byte, []int) {
	return file_proto_razpravljalnica_proto_rawDescGZIP(), []int{17}
}

func (x *GetMessagesByUserRequest) GetTopicId() int64 {
	if x != nil {
		return x.TopicId
	}
	return 0
}

func (x *GetMessagesByUserRequest) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

func (x *GetMessagesByUserRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *GetMessagesByUserRequest) GetRequestUserId() int64 {
	if x != nil {
		return x.RequestUserId
	}
	return 0
}

type GetMessagesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Messages      []*Message             `protobuf:"bytes,1,rep,name=messages,proto3" json:"messages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMessagesResponse) Reset() {
	*x = GetMessagesResponse{}
	mi := &file_proto_razpravljalnica_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMessagesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMessagesResponse) ProtoMessage() {}

func (x *GetMessagesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_razpravljalnica_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMessagesResponse.ProtoReflect.Descriptor instead.
func (*GetMessagesResponse) Descriptor() ([]byte, []int) {
	return file_proto_razpravljalnica_proto_rawDescGZIP(), []int{18}
}

func (x *GetMessagesResponse) GetMessages() []*Message {
	if x != nil {
		return x.Messages
	}
	return nil
}

type SubscribeTopicRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	TopicId        []int64                `protobuf:"varint,1,rep,packed,name=topic_id,json=topicId,proto3" json:"topic_id,omitempty"`
	UserId         int64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	FromMessageId  int64                  `protobuf:"varint,3,opt,name=from_message_id,json=fromMessageId,proto3" json:"from_message_id,omitempty"`
	SubscribeToken string                 `protobuf:"bytes,4,opt,name=subscribe_token,json=subscribeToken,proto3" json:"subscribe_token,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SubscribeTopicRequest) Reset() {
	*x = SubscribeTopicRequest{}
	mi := &file_proto_razpravljalnica_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeTopicRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeTopicRequest) ProtoMessage() {}

func (x *SubscribeTopicRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_razpravljalnica_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeTopicRequest.ProtoReflect.Descriptor instead.
func (*SubscribeTopicRequest) Descriptor() ([]byte, []int) {
	return file_proto_razpravljalnica_proto_rawDescGZIP(), []int{19}
}

func (x *SubscribeTopicRequest) GetTopicId() []int64 {
	if x != nil {
		return x.TopicId
	}
	return nil
}

func (x *SubscribeTopicRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *SubscribeTopicRequest) GetFromMessageId() int64 {
	if x != nil {
		return x.FromMessageId
	}
	return 0
}

func (x *SubscribeTopicRequest) GetSubscribeToken() string {
	if x != nil {
		return x.SubscribeToken
	}
	return ""
}

type SubscriptionNodeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	TopicId       []int64                `protobuf:"varint,2,rep,packed,name=topic_id,json=topicId,proto3" json:"topic_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscriptionNodeRequest) Reset() {
	*x = SubscriptionNodeRequest{}
	mi := &file_proto_razpravljalnica_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscriptionNodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscriptionNodeRequest) ProtoMessage() {}

func (x *SubscriptionNodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_razpravljalnica_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscriptionNodeRequest.ProtoReflect.Descriptor instead.
func (*SubscriptionNodeRequest) Descriptor() ([]byte, []int) {
	return file_proto_razpravljalnica_proto_rawDescGZIP(), []int{20}
}

func (x *SubscriptionNodeRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *SubscriptionNodeRequest) GetTopicId() []int64 {
	if x != nil {
		return x.TopicId
	}
	return nil
}

type SubscriptionNodeResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	SubscribeToken string                 `protobuf:"bytes,1,opt,name=subscribe_token,json=subscribeToken,proto3" json:"subscribe_token,omitempty"`
	Node           *NodeInfo              `protobuf:"bytes,2,opt,name=node,proto3" json:"node,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SubscriptionNodeResponse) Reset() {
	*x = SubscriptionNodeResponse{}
	mi := &file_proto_razpravljalnica_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscriptionNodeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscriptionNodeResponse) ProtoMessage() {}

func (x *SubscriptionNodeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_razpravljalnica_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscriptionNodeResponse.ProtoReflect.Descriptor instead.
func (*SubscriptionNodeResponse) Descriptor() ([]byte, []int) {
	return file_proto_razpravljalnica_proto_rawDescGZIP(), []int{21}
}

func (x *SubscriptionNodeResponse) GetSubscribeToken() string {
	if x != nil {
		return x.SubscribeToken
	}
	return ""
}

func (x *SubscriptionNodeResponse) GetNode() *NodeInfo {
	if x != nil {
		return x.Node
	}
	return nil
}

type MessageEvent struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	SequenceNumber int64                  `protobuf:"varint,1,opt,name=sequence_number,json=sequenceNumber,proto3" json:"sequence_number,omitempty"`
	Op             OpType                 `protobuf:"varint,2,opt,name=op,proto3,enum=razpravljalnica.OpType" json:"op,omitempty"`
	Message        *Message               `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	EventAt        *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=event_at,json=eventAt,proto3" json:"event_at,omitempty"`
	LikerId        int64                  `protobuf:"varint,5,opt,name=liker_id,json=likerId,proto3" json:"liker_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *MessageEvent) Reset() {
	*x = MessageEvent{}
	mi := &file_proto_razpravljalnica_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageEvent) ProtoMessage() {}

func (x *MessageEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_razpravljalnica_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageEvent.ProtoReflect.Descriptor instead.
func (*MessageEvent) Descriptor() ([]byte, []int) {
	return file_proto_razpravljalnica_proto_rawDescGZIP(), []int{22}
}

func (x *MessageEvent) GetSequenceNumber() int64 {
	if x != nil {
		return x.SequenceNumber
	}
	return 0
}

func (x *MessageEvent) GetOp() OpType {
	if x != nil {
		return x.Op
	}
	return OpType_OP_POST
}

func (x *MessageEvent) GetMessage() *Message {
	if x != nil {
		return x.Message
	}
	return nil
}

func (x *MessageEvent) GetEventAt() *timestamppb.Timestamp {
	if x != nil {
		return x.EventAt
	}
	return nil
}

func (x *MessageEvent) GetLikerId() int64 {
	if x != nil {
		return x.LikerId
	}
	return 0
}

type StateChangeNotification struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PrevNode      string                 `protobuf:"bytes,1,opt,name=prevNode,proto3" json:"prevNode,omitempty"`
	NextNode      string                 `protobuf:"bytes,2,opt,name=nextNode,proto3" json:"nextNode,omitempty"`
	IsHead        bool                   `protobuf:"varint,3,opt,name=is_head,json=isHead,proto3" json:"is_head,omitempty"`
	IsTail        bool                   `protobuf:"varint,4,opt,name=is_tail,json=isTail,proto3" json:"is_tail,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StateChangeNotification) Reset() {
	*x = StateChangeNotification{}
	mi := &file_proto_razpravljalnica_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StateChangeNotification) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StateChangeNotification) ProtoMessage() {}

func (x *StateChangeNotification) ProtoReflect() protoreflect.Message {
	mi := &file_proto_razpravljalnica_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StateChangeNotification.ProtoReflect.Descriptor instead.
func (*StateChangeNotification) Descriptor() ([]byte, []int) {
	return file_proto_razpravljalnica_proto_rawDescGZIP(), []int{23}
}

func (x *StateChangeNotification) GetPrevNode() string {
	if x != nil {
		return x.PrevNode
	}
	return ""
}

func (x *StateChangeNotification) GetNextNode() string {
	if x != nil {
		return x.NextNode
	}
	return ""
}

func (x *StateChangeNotification) GetIsHead() bool {
	if x != nil {
		return x.IsHead
	}
	return false
}

func (x *StateChangeNotification) GetIsTail() bool {
	if x != nil {
		return x.IsTail
	}
	return false
}

type JoinTopicRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TopicId       int64                  `protobuf:"varint,1,opt,name=topic_id,json=topicId,proto3" json:"topic_id,omitempty"`
	UserId        int64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinTopicRequest) Reset() {
	*x = JoinTopicRequest{}
	mi := &file_proto_razpravljalnica_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinTopicRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinTopicRequest) ProtoMessage() {}

func (x *JoinTopicRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_razpravljalnica_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinTopicRequest.ProtoReflect.Descriptor instead.
func (*JoinTopicRequest) Descriptor() ([]byte, []int) {
	return file_proto_razpravljalnica_proto_rawDescGZIP(), []int{24}
}

func (x *JoinTopicRequest) GetTopicId() int64 {
	if x != nil {
		return x.TopicId
	}
	return 0
}

func (x *JoinTopicRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type LeaveTopicRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TopicId       int64                  `protobuf:"varint,1,opt,name=topic_id,json=topicId,proto3" json:"topic_id,omitempty"`
	UserId        int64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LeaveTopicRequest) Reset() {
	*x = LeaveTopicRequest{}
	mi := &file_proto_razpravljalnica_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeaveTopicRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaveTopicRequest) ProtoMessage() {}

func (x *LeaveTopicRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_razpravljalnica_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaveTopicRequest.ProtoReflect.Descriptor instead.
func (*LeaveTopicRequest) Descriptor() ([]byte, []int) {
	return file_proto_razpravljalnica_proto_rawDescGZIP(), []int{25}
}

func (x *LeaveTopicRequest) GetTopicId() int64 {
	if x != nil {
		return x.TopicId
	}
	return 0
}

func (x *LeaveTopicRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type LeaderResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RaftId        string                 `protobuf:"bytes,1,opt,name=raft_id,json=raftId,proto3" json:"raft_id,omitempty"`
	Address       string                 `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LeaderResponse) Reset() {
	*x = LeaderResponse{}
	mi := &file_proto_razpravljalnica_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeaderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaderResponse) ProtoMessage() {}

func (x *LeaderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_razpravljalnica_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaderResponse.ProtoReflect.Descriptor instead.
func (*LeaderResponse) Descriptor() ([]byte, []int) {
	return file_proto_razpravljalnica_proto_rawDescGZIP(), []int{26}
}

func (x *LeaderResponse) GetRaftId() string {
	if x != nil {
		return x.RaftId
	}
	return ""
}

func (x *LeaderResponse) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

type ConfirmSyncedRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfirmSyncedRequest) Reset() {
	*x = ConfirmSyncedRequest{}
	mi := &file_proto_razpravljalnica_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfirmSyncedRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfirmSyncedRequest) ProtoMessage() {}

func (x *ConfirmSyncedRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_razpravljalnica_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfirmSyncedRequest.ProtoReflect.Descriptor instead.
func (*ConfirmSyncedRequest) Descriptor() ([]byte, []int) {
	return file_proto_razpravljalnica_proto_rawDescGZIP(), []int{27}
}

func (x *ConfirmSyncedRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

type GetClusterStateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Head          *NodeInfo              `protobuf:"bytes,1,opt,name=head,proto3" json:"head,omitempty"`
	Tail          *NodeInfo              `protobuf:"bytes,2,opt,name=tail,proto3" json:"tail,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetClusterStateResponse) Reset() {
	*x = GetClusterStateResponse{}
	mi := &file_proto_razpravljalnica_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetClusterStateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetClusterStateResponse) ProtoMessage() {}

func (x *GetClusterStateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_razpravljalnica_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetClusterStateResponse.ProtoReflect.Descriptor instead.
func (*GetClusterStateResponse) Descriptor() ([]byte, []int) {
	return file_proto_razpravljalnica_proto_rawDescGZIP(), []int{28}
}

func (x *GetClusterStateResponse) GetHead() *NodeInfo {
	if x != nil {
		return x.Head
	}
	return nil
}

func (x *GetClusterStateResponse) GetTail() *NodeInfo {
	if x != nil {
		return x.Tail
	}
	return nil
}

type RegisterNodeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Address       string                 `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterNodeRequest) Reset() {
	*x = RegisterNodeRequest{}
	mi := &file_proto_razpravljalnica_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterNodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterNodeRequest) ProtoMessage() {}

func (x *RegisterNodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_razpravljalnica_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterNodeRequest.ProtoReflect.Descriptor instead.
func (*RegisterNodeRequest) Descriptor() ([]byte, []int) {
	return file_proto_razpravljalnica_proto_rawDescGZIP(), []int{29}
}

func (x *RegisterNodeRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *RegisterNodeRequest) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

type HeartbeatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatRequest) Reset() {
	*x = HeartbeatRequest{}
	mi := &file_proto_razpravljalnica_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatRequest) ProtoMessage() {}

func (x *HeartbeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_razpravljalnica_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatRequest.ProtoReflect.Descriptor instead.
func (*HeartbeatRequest) Descriptor() ([]byte, []int) {
	return file_proto_razpravljalnica_proto_rawDescGZIP(), []int{30}
}

func (x *HeartbeatRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

type ChainStateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Chain         []*NodeInfo            `protobuf:"bytes,1,rep,name=chain,proto3" json:"chain,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChainStateResponse) Reset() {
	*x = ChainStateResponse{}
	mi := &file_proto_razpravljalnica_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChainStateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChainStateResponse) ProtoMessage() {}

func (x *ChainStateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_razpravljalnica_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChainStateResponse.ProtoReflect.Descriptor instead.
func (*ChainStateResponse) Descriptor() ([]byte, []int) {
	return file_proto_razpravljalnica_proto_rawDescGZIP(), []int{31}
}

func (x *ChainStateResponse) GetChain() []*NodeInfo {
	if x != nil {
		return x.Chain
	}
	return nil
}

type StreamLogRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FromSequence  int64                  `protobuf:"varint,1,opt,name=from_sequence,json=fromSequence,proto3" json:"from_sequence,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamLogRequest) Reset() {
	*x = StreamLogRequest{}
	mi := &file_proto_razpravljalnica_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamLogRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamLogRequest) ProtoMessage() {}

func (x *StreamLogRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_razpravljalnica_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamLogRequest.ProtoReflect.Descriptor instead.
func (*StreamLogRequest) Descriptor() ([]byte, []int) {
	return file_proto_razpravljalnica_proto_rawDescGZIP(), []int{32}
}

func (x *StreamLogRequest) GetFromSequence() int64 {
	if x != nil {
		return x.FromSequence
	}
	return 0
}

type ReplicationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Op            *WriteOp               `protobuf:"bytes,1,opt,name=op,proto3" json:"op,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReplicationRequest) Reset() {
	*x = ReplicationRequest{}
	mi := &file_proto_razpravljalnica_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReplicationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplicationRequest) ProtoMessage() {}

func (x *ReplicationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_razpravljalnica_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplicationRequest.ProtoReflect.Descriptor instead.
func (*ReplicationRequest) Descriptor() ([]byte, []int) {
	return file_proto_razpravljalnica_proto_rawDescGZIP(), []int{33}
}

func (x *ReplicationRequest) GetOp() *WriteOp {
	if x != nil {
		return x.Op
	}
	return nil
}

type WriteOp struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Operation:
	//
	//	*WriteOp_CreateUser
	//	*WriteOp_CreateTopic
	//	*WriteOp_PostMessage
	//	*WriteOp_LikeMessage
	//	*WriteOp_JoinTopic
	//	*WriteOp_LeaveTopic
	Operation     isWriteOp_Operation `protobuf_oneof:"operation"`
	Sequence      int64               `protobuf:"varint,7,opt,name=sequence,proto3" json:"sequence,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WriteOp) Reset() {
	*x = WriteOp{}
	mi := &file_proto_razpravljalnica_proto_msgTypes[34]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteOp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteOp) ProtoMessage() {}

func (x *WriteOp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_razpravljalnica_proto_msgTypes[34]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteOp.ProtoReflect.Descriptor instead.
func (*WriteOp) Descriptor() ([]byte, []int) {
	return file_proto_razpravljalnica_proto_rawDescGZIP(), []int{34}
}

func (x *WriteOp) GetOperation() isWriteOp_Operation {
	if x != nil {
		return x.Operation
	}
	return nil
}

func (x *WriteOp) GetCreateUser() *CreateUserRequest {
	if x != nil {
		if x, ok := x.Operation.(*WriteOp_CreateUser); ok {
			return x.CreateUser
		}
	}
	return nil
}

func (x *WriteOp) GetCreateTopic() *CreateTopicRequest {
	if x != nil {
		if x, ok := x.Operation.(*WriteOp_CreateTopic); ok {
			return x.CreateTopic
		}
	}
	return nil
}

func (x *WriteOp) GetPostMessage() *PostMessageRequest {
	if x != nil {
		if x, ok := x.Operation.(*WriteOp_PostMessage); ok {
			return x.PostMessage
		}
	}
	return nil
}

func (x *WriteOp) GetLikeMessage() *LikeMessageRequest {
	if x != nil {
		if x, ok := x.Operation.(*WriteOp_LikeMessage); ok {
			return x.LikeMessage
		}
	}
	return nil
}

func (x *WriteOp) GetJoinTopic() *JoinTopicRequest {
	if x != nil {
		if x, ok := x.Operation.(*WriteOp_JoinTopic); ok {
			return x.JoinTopic
		}
	}
	return nil
}

func (x *WriteOp) GetLeaveTopic() *LeaveTopicRequest {
	if x != nil {
		if x, ok := x.Operation.(*WriteOp_LeaveTopic); ok {
			return x.LeaveTopic
		}
	}
	return nil
}

func (x *WriteOp) GetSequence() int64 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

type isWriteOp_Operation interface {
	isWriteOp_Operation()
}

type WriteOp_CreateUser struct {
	CreateUser *CreateUserRequest `protobuf:"bytes,1,opt,name=create_user,json=createUser,proto3,oneof"`
}

type WriteOp_CreateTopic struct {
	CreateTopic *CreateTopicRequest `protobuf:"bytes,2,opt,name=create_topic,json=createTopic,proto3,oneof"`
}

type WriteOp_PostMessage struct {
	PostMessage *PostMessageRequest `protobuf:"bytes,3,opt,name=post_message,json=postMessage,proto3,oneof"`
}

type WriteOp_LikeMessage struct {
	LikeMessage *LikeMessageRequest `protobuf:"bytes,4,opt,name=like_message,json=likeMessage,proto3,oneof"`
}

type WriteOp_JoinTopic struct {
	JoinTopic *JoinTopicRequest `protobuf:"bytes,5,opt,name=join_topic,json=joinTopic,proto3,oneof"`
}

type WriteOp_LeaveTopic struct {
	LeaveTopic *LeaveTopicRequest `protobuf:"bytes,6,opt,name=leave_topic,json=leaveTopic,proto3,oneof"`
}

func (*WriteOp_CreateUser) isWriteOp_Operation() {}

func (*WriteOp_CreateTopic) isWriteOp_Operation() {}

func (*WriteOp_PostMessage) isWriteOp_Operation() {}

func (*WriteOp_LikeMessage) isWriteOp_Operation() {}

func (*WriteOp_JoinTopic) isWriteOp_Operation() {}

func (*WriteOp_LeaveTopic) isWriteOp_Operation() {}

type AcknowledgeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sequence      int64                  `protobuf:"varint,1,opt,name=sequence,proto3" json:"sequence,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AcknowledgeRequest) Reset() {
	*x = AcknowledgeRequest{}
	mi := &file_proto_razpravljalnica_proto_msgTypes[35]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AcknowledgeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AcknowledgeRequest) ProtoMessage() {}

func (x *AcknowledgeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_razpravljalnica_proto_msgTypes[35]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AcknowledgeRequest.ProtoReflect.Descriptor instead.
func (*AcknowledgeRequest) Descriptor() ([]byte, []int) {
	return file_proto_razpravljalnica_proto_rawDescGZIP(), []int{35}
}

func (x *AcknowledgeRequest) GetSequence() int64 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

type GetLastAckedResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sequence      int64                  `protobuf:"varint,1,opt,name=sequence,proto3" json:"sequence,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLastAckedResponse) Reset() {
	*x = GetLastAckedResponse{}
	mi := &file_proto_razpravljalnica_proto_msgTypes[36]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLastAckedResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLastAckedResponse) ProtoMessage() {}

func (x *GetLastAckedResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_razpravljalnica_proto_msgTypes[36]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLastAckedResponse.ProtoReflect.Descriptor instead.
func (*GetLastAckedResponse) Descriptor() ([]byte, []int) {
	return file_proto_razpravljalnica_proto_rawDescGZIP(), []int{36}
}

func (x *GetLastAckedResponse) GetSequence() int64 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

type GetLastSequenceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sequence      int64                  `protobuf:"varint,1,opt,name=sequence,proto3" json:"sequence,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLastSequenceResponse) Reset() {
	*x = GetLastSequenceResponse{}
	mi := &file_proto_razpravljalnica_proto_msgTypes[37]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLastSequenceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLastSequenceResponse) ProtoMessage() {}

func (x *GetLastSequenceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_razpravljalnica_proto_msgTypes[37]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLastSequenceResponse.ProtoReflect.Descriptor instead.
func (*GetLastSequenceResponse) Descriptor() ([]byte, []int) {
	return file_proto_razpravljalnica_proto_rawDescGZIP(), []int{37}
}

func (x *GetLastSequenceResponse) GetSequence() int64 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

var File_proto_razpravljalnica_proto protoreflect.FileDescriptor

const file_proto_razpravljalnica_proto_rawDesc = "" +
	"\n" +
	"\x1bproto/razpravljalnica.proto\x12\x0frazpravljalnica\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"c\n" +
	"\x04User\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12#\n" +
	"\rpassword_hash\x18\x03 \x01(\tR\fpasswordHash\x12\x12\n" +
	"\x04salt\x18\x04 \x01(\tR\x04salt\"+\n" +
	"\x05Topic\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"\xec\x01\n" +
	"\aMessage\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x19\n" +
	"\btopic_id\x18\x02 \x01(\x03R\atopicId\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\x03R\x06userId\x12\x12\n" +
	"\x04text\x18\x04 \x01(\tR\x04text\x129\n" +
	"\n" +
	"created_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"topic_name\x18\x06 \x01(\tR\ttopicName\x12\x14\n" +
	"\x05likes\x18\a \x01(\x05R\x05likes\x12\x19\n" +
	"\bis_liked\x18\b \x01(\bR\aisLiked\"Y\n" +
	"\x04Like\x12\x19\n" +
	"\btopic_id\x18\x01 \x01(\x03R\atopicId\x12\x1d\n" +
	"\n" +
	"message_id\x18\x02 \x01(\x03R\tmessageId\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\x03R\x06userId\"=\n" +
	"\bNodeInfo\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x18\n" +
	"\aaddress\x18\x02 \x01(\tR\aaddress\"W\n" +
	"\x11CreateUserRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\x12\x12\n" +
	"\x04salt\x18\x03 \x01(\tR\x04salt\">\n" +
	"\fLoginRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"$\n" +
	"\x0eGetUserRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"$\n" +
	"\x12GetUserByIdRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"A\n" +
	"\x12CreateTopicRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId\"%\n" +
	"\x0fGetTopicRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"\\\n" +
	"\x12PostMessageRequest\x12\x19\n" +
	"\btopic_id\x18\x01 \x01(\x03R\atopicId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId\x12\x12\n" +
	"\x04text\x18\x03 \x01(\tR\x04text\"{\n" +
	"\x12LikeMessageRequest\x12\x19\n" +
	"\btopic_id\x18\x01 \x01(\x03R\atopicId\x12\x1d\n" +
	"\n" +
	"message_id\x18\x02 \x01(\x03R\tmessageId\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\x03R\x06userId\x12\x12\n" +
	"\x04like\x18\x04 \x01(\bR\x04like\",\n" +
	"\x11ListTopicsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\"4\n" +
	"\x19ListJoinableTopicsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\"D\n" +
	"\x12ListTopicsResponse\x12.\n" +
	"\x06topics\x18\x01 \x03(\v2\x16.razpravljalnica.TopicR\x06topics\"\x95\x01\n" +
	"\x12GetMessagesRequest\x12\x19\n" +
	"\btopic_id\x18\x01 \x01(\x03R\atopicId\x12&\n" +
	"\x0ffrom_message_id\x18\x02 \x01(\x03R\rfromMessageId\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x05R\x05limit\x12&\n" +
	"\x0frequest_user_id\x18\x04 \x01(\x03R\rrequestUserId\"\x90\x01\n" +
	"\x18GetMessagesByUserRequest\x12\x19\n" +
	"\btopic_id\x18\x01 \x01(\x03R\atopicId\x12\x1b\n" +
	"\tuser_name\x18\x02 \x01(\tR\buserName\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x05R\x05limit\x12&\n" +
	"\x0frequest_user_id\x18\x04 \x01(\x03R\rrequestUserId\"K\n" +
	"\x13GetMessagesResponse\x124\n" +
	"\bmessages\x18\x01 \x03(\v2\x18.razpravljalnica.MessageR\bmessages\"\x9c\x01\n" +
	"\x15SubscribeTopicRequest\x12\x19\n" +
	"\btopic_id\x18\x01 \x03(\x03R\atopicId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId\x12&\n" +
	"\x0ffrom_message_id\x18\x03 \x01(\x03R\rfromMessageId\x12'\n" +
	"\x0fsubscribe_token\x18\x04 \x01(\tR\x0esubscribeToken\"M\n" +
	"\x17SubscriptionNodeRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x19\n" +
	"\btopic_id\x18\x02 \x03(\x03R\atopicId\"r\n" +
	"\x18SubscriptionNodeResponse\x12'\n" +
	"\x0fsubscribe_token\x18\x01 \x01(\tR\x0esubscribeToken\x12-\n" +
	"\x04node\x18\x02 \x01(\v2\x19.razpravljalnica.NodeInfoR\x04node\"\xe6\x01\n" +
	"\fMessageEvent\x12'\n" +
	"\x0fsequence_number\x18\x01 \x01(\x03R\x0esequenceNumber\x12'\n" +
	"\x02op\x18\x02 \x01(\x0e2\x17.razpravljalnica.OpTypeR\x02op\x122\n" +
	"\amessage\x18\x03 \x01(\v2\x18.razpravljalnica.MessageR\amessage\x125\n" +
	"\bevent_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\aeventAt\x12\x19\n" +
	"\bliker_id\x18\x05 \x01(\x03R\alikerId\"\x83\x01\n" +
	"\x17StateChangeNotification\x12\x1a\n" +
	"\bprevNode\x18\x01 \x01(\tR\bprevNode\x12\x1a\n" +
	"\bnextNode\x18\x02 \x01(\tR\bnextNode\x12\x17\n" +
	"\ais_head\x18\x03 \x01(\bR\x06isHead\x12\x17\n" +
	"\ais_tail\x18\x04 \x01(\bR\x06isTail\"F\n" +
	"\x10JoinTopicRequest\x12\x19\n" +
	"\btopic_id\x18\x01 \x01(\x03R\atopicId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId\"G\n" +
	"\x11LeaveTopicRequest\x12\x19\n" +
	"\btopic_id\x18\x01 \x01(\x03R\atopicId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId\"C\n" +
	"\x0eLeaderResponse\x12\x17\n" +
	"\araft_id\x18\x01 \x01(\tR\x06raftId\x12\x18\n" +
	"\aaddress\x18\x02 \x01(\tR\aaddress\"/\n" +
	"\x14ConfirmSyncedRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\"w\n" +
	"\x17GetClusterStateResponse\x12-\n" +
	"\x04head\x18\x01 \x01(\v2\x19.razpravljalnica.NodeInfoR\x04head\x12-\n" +
	"\x04tail\x18\x02 \x01(\v2\x19.razpravljalnica.NodeInfoR\x04tail\"H\n" +
	"\x13RegisterNodeRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x18\n" +
	"\aaddress\x18\x02 \x01(\tR\aaddress\"+\n" +
	"\x10HeartbeatRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\"E\n" +
	"\x12ChainStateResponse\x12/\n" +
	"\x05chain\x18\x01 \x03(\v2\x19.razpravljalnica.NodeInfoR\x05chain\"7\n" +
	"\x10StreamLogRequest\x12#\n" +
	"\rfrom_sequence\x18\x01 \x01(\x03R\ffromSequence\">\n" +
	"\x12ReplicationRequest\x12(\n" +
	"\x02op\x18\x01 \x01(\v2\x18.razpravljalnica.WriteOpR\x02op\"\xe2\x03\n" +
	"\aWriteOp\x12E\n" +
	"\vcreate_user\x18\x01 \x01(\v2\".razpravljalnica.CreateUserRequestH\x00R\n" +
	"createUser\x12H\n" +
	"\fcreate_topic\x18\x02 \x01(\v2#.razpravljalnica.CreateTopicRequestH\x00R\vcreateTopic\x12H\n" +
	"\fpost_message\x18\x03 \x01(\v2#.razpravljalnica.PostMessageRequestH\x00R\vpostMessage\x12H\n" +
	"\flike_message\x18\x04 \x01(\v2#.razpravljalnica.LikeMessageRequestH\x00R\vlikeMessage\x12B\n" +
	"\n" +
	"join_topic\x18\x05 \x01(\v2!.razpravljalnica.JoinTopicRequestH\x00R\tjoinTopic\x12E\n" +
	"\vleave_topic\x18\x06 \x01(\v2\".razpravljalnica.LeaveTopicRequestH\x00R\n" +
	"leaveTopic\x12\x1a\n" +
	"\bsequence\x18\a \x01(\x03R\bsequenceB\v\n" +
	"\toperation\"0\n" +
	"\x12AcknowledgeRequest\x12\x1a\n" +
	"\bsequence\x18\x01 \x01(\x03R\bsequence\"2\n" +
	"\x14GetLastAckedResponse\x12\x1a\n" +
	"\bsequence\x18\x01 \x01(\x03R\bsequence\"5\n" +
	"\x17GetLastSequenceResponse\x12\x1a\n" +
	"\bsequence\x18\x01 \x01(\x03R\bsequence*1\n" +
	"\x06OpType\x12\v\n" +
	"\aOP_POST\x10\x00\x12\v\n" +
	"\aOP_LIKE\x10\x01\x12\r\n" +
	"\tOP_UNLIKE\x10\x022\xce\v\n" +
	"\fMessageBoard\x12U\n" +
	"\x11NotifyStateChange\x12(.razpravljalnica.StateChangeNotification\x1a\x16.google.protobuf.Empty\x12G\n" +
	"\n" +
	"CreateUser\x12\".razpravljalnica.CreateUserRequest\x1a\x15.razpravljalnica.User\x12=\n" +
	"\x05Login\x12\x1d.razpravljalnica.LoginRequest\x1a\x15.razpravljalnica.User\x12A\n" +
	"\aGetUser\x12\x1f.razpravljalnica.GetUserRequest\x1a\x15.razpravljalnica.User\x12I\n" +
	"\vGetUserById\x12#.razpravljalnica.GetUserByIdRequest\x1a\x15.razpravljalnica.User\x12J\n" +
	"\vCreateTopic\x12#.razpravljalnica.CreateTopicRequest\x1a\x16.razpravljalnica.Topic\x12D\n" +
	"\bGetTopic\x12 .razpravljalnica.GetTopicRequest\x1a\x16.razpravljalnica.Topic\x12L\n" +
	"\vPostMessage\x12#.razpravljalnica.PostMessageRequest\x1a\x18.razpravljalnica.Message\x12L\n" +
	"\vLikeMessage\x12#.razpravljalnica.LikeMessageRequest\x1a\x18.razpravljalnica.Message\x12j\n" +
	"\x13GetSubscriptionNode\x12(.razpravljalnica.SubscriptionNodeRequest\x1a).razpravljalnica.SubscriptionNodeResponse\x12U\n" +
	"\n" +
	"ListTopics\x12\".razpravljalnica.ListTopicsRequest\x1a#.razpravljalnica.ListTopicsResponse\x12X\n" +
	"\vGetMessages\x12#.razpravljalnica.GetMessagesRequest\x1a$.razpravljalnica.GetMessagesResponse\x12d\n" +
	"\x11GetMessagesByUser\x12).razpravljalnica.GetMessagesByUserRequest\x1a$.razpravljalnica.GetMessagesResponse\x12Y\n" +
	"\x0eSubscribeTopic\x12&.razpravljalnica.SubscribeTopicRequest\x1a\x1d.razpravljalnica.MessageEvent0\x01\x12F\n" +
	"\tJoinTopic\x12!.razpravljalnica.JoinTopicRequest\x1a\x16.google.protobuf.Empty\x12H\n" +
	"\n" +
	"LeaveTopic\x12\".razpravljalnica.LeaveTopicRequest\x1a\x16.google.protobuf.Empty\x12L\n" +
	"\rListAllTopics\x12\x16.google.protobuf.Empty\x1a#.razpravljalnica.ListTopicsResponse\x12e\n" +
	"\x12ListJoinableTopics\x12*.razpravljalnica.ListJoinableTopicsRequest\x1a#.razpravljalnica.ListTopicsResponse2\xdd\x03\n" +
	"\fControlPlane\x12D\n" +
	"\tGetLeader\x12\x16.google.protobuf.Empty\x1a\x1f.razpravljalnica.LeaderResponse\x12S\n" +
	"\x0fGetClusterState\x12\x16.google.protobuf.Empty\x1a(.razpravljalnica.GetClusterStateResponse\x12L\n" +
	"\fRegisterNode\x12$.razpravljalnica.RegisterNodeRequest\x1a\x16.google.protobuf.Empty\x12F\n" +
	"\tHeartbeat\x12!.razpravljalnica.HeartbeatRequest\x1a\x16.google.protobuf.Empty\x12L\n" +
	"\rGetChainState\x12\x16.google.protobuf.Empty\x1a#.razpravljalnica.ChainStateResponse\x12N\n" +
	"\rConfirmSynced\x12%.razpravljalnica.ConfirmSyncedRequest\x1a\x16.google.protobuf.Empty2\xe3\x03\n" +
	"\vReplication\x12M\n" +
	"\x0eReplicateWrite\x12#.razpravljalnica.ReplicationRequest\x1a\x16.google.protobuf.Empty\x12J\n" +
	"\tStreamLog\x12!.razpravljalnica.StreamLogRequest\x1a\x18.razpravljalnica.WriteOp0\x01\x12D\n" +
	"\vNotifyEvent\x12\x1d.razpravljalnica.MessageEvent\x1a\x16.google.protobuf.Empty\x12O\n" +
	"\x10AcknowledgeWrite\x12#.razpravljalnica.AcknowledgeRequest\x1a\x16.google.protobuf.Empty\x12M\n" +
	"\fGetLastAcked\x12\x16.google.protobuf.Empty\x1a%.razpravljalnica.GetLastAckedResponse\x12S\n" +
	"\x0fGetLastSequence\x12\x16.google.protobuf.Empty\x1a(.razpravljalnica.GetLastSequenceResponseB\x12Z\x10/razpravljalnicab\x06proto3"

var (
	file_proto_razpravljalnica_proto_rawDescOnce sync.Once
	file_proto_razpravljalnica_proto_rawDescData []byte
)

func file_proto_razpravljalnica_proto_rawDescGZIP() []byte {
	file_proto_razpravljalnica_proto_rawDescOnce.Do(func() {
		file_proto_razpravljalnica_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_razpravljalnica_proto_rawDesc), len(file_proto_razpravljalnica_proto_rawDesc)))
	})
	return file_proto_razpravljalnica_proto_rawDescData
}

var file_proto_razpravljalnica_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_razpravljalnica_proto_msgTypes = make([]protoimpl.MessageInfo, 38)
var file_proto_razpravljalnica_proto_goTypes = []any{
	(OpType)(0),                       // 0: razpravljalnica.OpType
	(*User)(nil),                      // 1: razpravljalnica.User
	(*Topic)(nil),                     // 2: razpravljalnica.Topic
	(*Message)(nil),                   // 3: razpravljalnica.Message
	(*Like)(nil),                      // 4: razpravljalnica.Like
	(*NodeInfo)(nil),                  // 5: razpravljalnica.NodeInfo
	(*CreateUserRequest)(nil),         // 6: razpravljalnica.CreateUserRequest
	(*LoginRequest)(nil),              // 7: razpravljalnica.LoginRequest
	(*GetUserRequest)(nil),            // 8: razpravljalnica.GetUserRequest
	(*GetUserByIdRequest)(nil),        // 9: razpravljalnica.GetUserByIdRequest
	(*CreateTopicRequest)(nil),        // 10: razpravljalnica.CreateTopicRequest
	(*GetTopicRequest)(nil),           // 11: razpravljalnica.GetTopicRequest
	(*PostMessageRequest)(nil),        // 12: razpravljalnica.PostMessageRequest
	(*LikeMessageRequest)(nil),        // 13: razpravljalnica.LikeMessageRequest
	(*ListTopicsRequest)(nil),         // 14: razpravljalnica.ListTopicsRequest
	(*ListJoinableTopicsRequest)(nil), // 15: razpravljalnica.ListJoinableTopicsRequest
	(*ListTopicsResponse)(nil),        // 16: razpravljalnica.ListTopicsResponse
	(*GetMessagesRequest)(nil),        // 17: razpravljalnica.GetMessagesRequest
	(*GetMessagesByUserRequest)(nil),  // 18: razpravljalnica.GetMessagesByUserRequest
	(*GetMessagesResponse)(nil),       // 19: razpravljalnica.GetMessagesResponse
	(*SubscribeTopicRequest)(nil),     // 20: razpravljalnica.SubscribeTopicRequest
	(*SubscriptionNodeRequest)(nil),   // 21: razpravljalnica.SubscriptionNodeRequest
	(*SubscriptionNodeResponse)(nil),  // 22: razpravljalnica.SubscriptionNodeResponse
	(*MessageEvent)(nil),              // 23: razpravljalnica.MessageEvent
	(*StateChangeNotification)(nil),   // 24: razpravljalnica.StateChangeNotification
	(*JoinTopicRequest)(nil),          // 25: razpravljalnica.JoinTopicRequest
	(*LeaveTopicRequest)(nil),         // 26: razpravljalnica.LeaveTopicRequest
	(*LeaderResponse)(nil),            // 27: razpravljalnica.LeaderResponse
	(*ConfirmSyncedRequest)(nil),      // 28: razpravljalnica.ConfirmSyncedRequest
	(*GetClusterStateResponse)(nil),   // 29: razpravljalnica.GetClusterStateResponse
	(*RegisterNodeRequest)(nil),       // 30: razpravljalnica.RegisterNodeRequest
	(*HeartbeatRequest)(nil),          // 31: razpravljalnica.HeartbeatRequest
	(*ChainStateResponse)(nil),        // 32: razpravljalnica.ChainStateResponse
	(*StreamLogRequest)(nil),          // 33: razpravljalnica.StreamLogRequest
	(*ReplicationRequest)(nil),        // 34: razpravljalnica.ReplicationRequest
	(*WriteOp)(nil),                   // 35: razpravljalnica.WriteOp
	(*AcknowledgeRequest)(nil),        // 36: razpravljalnica.AcknowledgeRequest
	(*GetLastAckedResponse)(nil),      // 37: razpravljalnica.GetLastAckedResponse
	(*GetLastSequenceResponse)(nil),   // 38: razpravljalnica.GetLastSequenceResponse
	(*timestamppb.Timestamp)(nil),     // 39: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),             // 40: google.protobuf.Empty
}
var file_proto_razpravljalnica_proto_depIdxs = []int32{
	39, // 0: razpravljalnica.Message.created_at:type_name -> google.protobuf.Timestamp
	2,  // 1: razpravljalnica.ListTopicsResponse.topics:type_name -> razpravljalnica.Topic
	3,  // 2: razpravljalnica.GetMessagesResponse.messages:type_name -> razpravljalnica.Message
	5,  // 3: razpravljalnica.SubscriptionNodeResponse.node:type_name -> razpravljalnica.NodeInfo
	0,  // 4: razpravljalnica.MessageEvent.op:type_name -> razpravljalnica.OpType
	3,  // 5: razpravljalnica.MessageEvent.message:type_name -> razpravljalnica.Message
	39, // 6: razpravljalnica.MessageEvent.event_at:type_name -> google.protobuf.Timestamp
	5,  // 7: razpravljalnica.GetClusterStateResponse.head:type_name -> razpravljalnica.NodeInfo
	5,  // 8: razpravljalnica.GetClusterStateResponse.tail:type_name -> razpravljalnica.NodeInfo
	5,  // 9: razpravljalnica.ChainStateResponse.chain:type_name -> razpravljalnica.NodeInfo
	35, // 10: razpravljalnica.ReplicationRequest.op:type_name -> razpravljalnica.WriteOp
	6,  // 11: razpravljalnica.WriteOp.create_user:type_name -> razpravljalnica.CreateUserRequest
	10, // 12: razpravljalnica.WriteOp.create_topic:type_name -> razpravljalnica.CreateTopicRequest
	12, // 13: razpravljalnica.WriteOp.post_message:type_name -> razpravljalnica.PostMessageRequest
	13, // 14: razpravljalnica.WriteOp.like_message:type_name -> razpravljalnica.LikeMessageRequest
	25, // 15: razpravljalnica.WriteOp.join_topic:type_name -> razpravljalnica.JoinTopicRequest
	26, // 16: razpravljalnica.WriteOp.leave_topic:type_name -> razpravljalnica.LeaveTopicRequest
	24, // 17: razpravljalnica.MessageBoard.NotifyStateChange:input_type -> razpravljalnica.StateChangeNotification
	6,  // 18: razpravljalnica.MessageBoard.CreateUser:input_type -> razpravljalnica.CreateUserRequest
	7,  // 19: razpravljalnica.MessageBoard.Login:input_type -> razpravljalnica.LoginRequest
	8,  // 20: razpravljalnica.MessageBoard.GetUser:input_type -> razpravljalnica.GetUserRequest
	9,  // 21: razpravljalnica.MessageBoard.GetUserById:input_type -> razpravljalnica.GetUserByIdRequest
	10, // 22: razpravljalnica.MessageBoard.CreateTopic:input_type -> razpravljalnica.CreateTopicRequest
	11, // 23: razpravljalnica.MessageBoard.GetTopic:input_type -> razpravljalnica.GetTopicRequest
	12, // 24: razpravljalnica.MessageBoard.PostMessage:input_type -> razpravljalnica.PostMessageRequest
	13, // 25: razpravljalnica.MessageBoard.LikeMessage:input_type -> razpravljalnica.LikeMessageRequest
	21, // 26: razpravljalnica.MessageBoard.GetSubscriptionNode:input_type -> razpravljalnica.SubscriptionNodeRequest
	14, // 27: razpravljalnica.MessageBoard.ListTopics:input_type -> razpravljalnica.ListTopicsRequest
	17, // 28: razpravljalnica.MessageBoard.GetMessages:input_type -> razpravljalnica.GetMessagesRequest
	18, // 29: razpravljalnica.MessageBoard.GetMessagesByUser:input_type -> razpravljalnica.GetMessagesByUserRequest
	20, // 30: razpravljalnica.MessageBoard.SubscribeTopic:input_type -> razpravljalnica.SubscribeTopicRequest
	25, // 31: razpravljalnica.MessageBoard.JoinTopic:input_type -> razpravljalnica.JoinTopicRequest
	26, // 32: razpravljalnica.MessageBoard.LeaveTopic:input_type -> razpravljalnica.LeaveTopicRequest
	40, // 33: razpravljalnica.MessageBoard.ListAllTopics:input_type -> google.protobuf.Empty
	15, // 34: razpravljalnica.MessageBoard.ListJoinableTopics:input_type -> razpravljalnica.ListJoinableTopicsRequest
	40, // 35: razpravljalnica.ControlPlane.GetLeader:input_type -> google.protobuf.Empty
	40, // 36: razpravljalnica.ControlPlane.GetClusterState:input_type -> google.protobuf.Empty
	30, // 37: razpravljalnica.ControlPlane.RegisterNode:input_type -> razpravljalnica.RegisterNodeRequest
	31, // 38: razpravljalnica.ControlPlane.Heartbeat:input_type -> razpravljalnica.HeartbeatRequest
	40, // 39: razpravljalnica.ControlPlane.GetChainState:input_type -> google.protobuf.Empty
	28, // 40: razpravljalnica.ControlPlane.ConfirmSynced:input_type -> razpravljalnica.ConfirmSyncedRequest
	34, // 41: razpravljalnica.Replication.ReplicateWrite:input_type -> razpravljalnica.ReplicationRequest
	33, // 42: razpravljalnica.Replication.StreamLog:input_type -> razpravljalnica.StreamLogRequest
	23, // 43: razpravljalnica.Replication.NotifyEvent:input_type -> razpravljalnica.MessageEvent
	36, // 44: razpravljalnica.Replication.AcknowledgeWrite:input_type -> razpravljalnica.AcknowledgeRequest
	40, // 45: razpravljalnica.Replication.GetLastAcked:input_type -> google.protobuf.Empty
	40, // 46: razpravljalnica.Replication.GetLastSequence:input_type -> google.protobuf.Empty
	40, // 47: razpravljalnica.MessageBoard.NotifyStateChange:output_type -> google.protobuf.Empty
	1,  // 48: razpravljalnica.MessageBoard.CreateUser:output_type -> razpravljalnica.User
	1,  // 49: razpravljalnica.MessageBoard.Login:output_type -> razpravljalnica.User
	1,  // 50: razpravljalnica.MessageBoard.GetUser:output_type -> razpravljalnica.User
	1,  // 51: razpravljalnica.MessageBoard.GetUserById:output_type -> razpravljalnica.User
	2,  // 52: razpravljalnica.MessageBoard.CreateTopic:output_type -> razpravljalnica.Topic
	2,  // 53: razpravljalnica.MessageBoard.GetTopic:output_type -> razpravljalnica.Topic
	3,  // 54: razpravljalnica.MessageBoard.PostMessage:output_type -> razpravljalnica.Message
	3,  // 55: razpravljalnica.MessageBoard.LikeMessage:output_type -> razpravljalnica.Message
	22, // 56: razpravljalnica.MessageBoard.GetSubscriptionNode:output_type -> razpravljalnica.SubscriptionNodeResponse
	16, // 57: razpravljalnica.MessageBoard.ListTopics:output_type -> razpravljalnica.ListTopicsResponse
	19, // 58: razpravljalnica.MessageBoard.GetMessages:output_type -> razpravljalnica.GetMessagesResponse
	19, // 59: razpravljalnica.MessageBoard.GetMessagesByUser:output_type -> razpravljalnica.GetMessagesResponse
	23, // 60: razpravljalnica.MessageBoard.SubscribeTopic:output_type -> razpravljalnica.MessageEvent
	40, // 61: razpravljalnica.MessageBoard.JoinTopic:output_type -> google.protobuf.Empty
	40, // 62: razpravljalnica.MessageBoard.LeaveTopic:output_type -> google.protobuf.Empty
	16, // 63: razpravljalnica.MessageBoard.ListAllTopics:output_type -> razpravljalnica.ListTopicsResponse
	16, // 64: razpravljalnica.MessageBoard.ListJoinableTopics:output_type -> razpravljalnica.ListTopicsResponse
	27, // 65: razpravljalnica.ControlPlane.GetLeader:output_type -> razpravljalnica.LeaderResponse
	29, // 66: razpravljalnica.ControlPlane.GetClusterState:output_type -> razpravljalnica.GetClusterStateResponse
	40, // 67: razpravljalnica.ControlPlane.RegisterNode:output_type -> google.protobuf.Empty
	40, // 68: razpravljalnica.ControlPlane.Heartbeat:output_type -> google.protobuf.Empty
	32, // 69: razpravljalnica.ControlPlane.GetChainState:output_type -> razpravljalnica.ChainStateResponse
	40, // 70: razpravljalnica.ControlPlane.ConfirmSynced:output_type -> google.protobuf.Empty
	40, // 71: razpravljalnica.Replication.ReplicateWrite:output_type -> google.protobuf.Empty
	35, // 72: razpravljalnica.Replication.StreamLog:output_type -> razpravljalnica.WriteOp
	40, // 73: razpravljalnica.Replication.NotifyEvent:output_type -> google.protobuf.Empty
	40, // 74: razpravljalnica.Replication.AcknowledgeWrite:output_type -> google.protobuf.Empty
	37, // 75: razpravljalnica.Replication.GetLastAcked:output_type -> razpravljalnica.GetLastAckedResponse
	38, // 76: razpravljalnica.Replication.GetLastSequence:output_type -> razpravljalnica.GetLastSequenceResponse
	47, // [47:77] is the sub-list for method output_type
	17, // [17:47] is the sub-list for method input_type
	17, // [17:17] is the sub-list for extension type_name
	17, // [17:17] is the sub-list for extension extendee
	0,  // [0:17] is the sub-list for field type_name
}

func init() { file_proto_razpravljalnica_proto_init() }
func file_proto_razpravljalnica_proto_init() {
	if File_proto_razpravljalnica_proto != nil {
		return
	}
	file_proto_razpravljalnica_proto_msgTypes[34].OneofWrappers = []any{
		(*WriteOp_CreateUser)(nil),
		(*WriteOp_CreateTopic)(nil),
		(*WriteOp_PostMessage)(nil),
		(*WriteOp_LikeMessage)(nil),
		(*WriteOp_JoinTopic)(nil),
		(*WriteOp_LeaveTopic)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_razpravljalnica_proto_rawDesc), len(file_proto_razpravljalnica_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   38,
			NumExtensions: 0,
			NumServices:   3,
		},
		GoTypes:           file_proto_razpravljalnica_proto_goTypes,
		DependencyIndexes: file_proto_razpravljalnica_proto_depIdxs,
		EnumInfos:         file_proto_razpravljalnica_proto_enumTypes,
		MessageInfos:      file_proto_razpravljalnica_proto_msgTypes,
	}.Build()
	File_proto_razpravljalnica_proto = out.File
	file_proto_razpravljalnica_proto_goTypes = nil
	file_proto_razpravljalnica_proto_depIdxs = nil
}
